from pydantic import BaseModel, Field, computed_field

from app.schemas.chunk import DocumentChunk


class EmbeddingVector(BaseModel):
    """One vector generated by an embedding provider."""

    values: list[float] = Field(min_length=1)

    @computed_field
    @property
    def dimension(self) -> int:
        """Return the number of dimensions in the vector."""

        return len(self.values)


class EmbeddedChunk(BaseModel):
    """A document chunk combined with its embedding vector."""

    chunk: DocumentChunk
    embedding: EmbeddingVector
    model_name: str = Field(min_length=1)
    provider_name: str = Field(min_length=1)


class EmbeddingBatchResult(BaseModel):
    """Result of embedding multiple document chunks."""

    items: list[EmbeddedChunk]
    provider_name: str = Field(min_length=1)
    model_name: str = Field(min_length=1)
    dimension: int = Field(ge=1)

    @computed_field
    @property
    def item_count(self) -> int:
        """Return the number of embedded chunks."""

        return len(self.items)
