ORCHESTRATOR_AGENT_NAME = "orchestrator"
ORCHESTRATOR_PLANNER_VERSION = "1.0.0"

ORCHESTRATOR_ALLOWED_SPECIALIST_AGENTS = (
    "proposal-analysis",
    "risk-report",
    "vendor-research",
)

ORCHESTRATOR_MAXIMUM_TASKS = 3
ORCHESTRATOR_MAXIMUM_STEPS = 12
ORCHESTRATOR_MAXIMUM_RETRIES_PER_TASK = 1
